import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextUIProvider from "@components/NextUIProvider";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import { LoginLink, LogoutLink } from "@kinde-oss/kinde-auth-nextjs/components";
import { getKindeServerSession } from "@kinde-oss/kinde-auth-nextjs/server";
import Nav from "@components/navigation/Nav";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Patientio AI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isAuthenticated, getUser } = getKindeServerSession();
  const user = await getUser();

  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <NextTopLoader
          color="#005efb"
          initialPosition={0.08}
          crawlSpeed={200}
          showSpinner={false}
          height={3}
          crawl={true}
          easing="ease-in-out"
          speed={200}
          shadow="0 0 10px #ffff,0 0 5px #ffffD"
          zIndex={1600}
        />
        {(await isAuthenticated()) ? (
          <NextUIProvider>{children}</NextUIProvider>
        ) : (
          <div>
            This page is protected, please <LoginLink>Login</LoginLink> to view
            it
          </div>
        )}
      </body>
    </html>
  );
}
